version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:

  AfterInstall:
    - location: scripts/build_app.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/deploy_app.sh
      timeout: 300
      runas: ec2-user
