version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/build_app.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/deploy_app.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
