name: Deploy to EC2 via SSM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}

    - name: Deploy via SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:name,Values=root-backend-instance" \
          --parameters commands='[
            "cd /home/${{ secrets.EC2_USER }}/app",
            "git pull origin main || git clone https://github.com/GrongoTheGrog/cloud_storage_app.git .",
            "mvn clean package -Dmaven.test.skip=true",
            "nohup java -jar target/*.jar > app.log 2>&1 &"
          ]' \
          --region ${{ secrets.AWS_REGION }}
