on: 
  pull_request:
    types: [closes]
    branches: [main]
  push:
    branches: [main]


jobs:
  deploy:
    environment: secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Push files to EC2
      run: |
        ssh -A ${{ secrets.EC2_BASTION_USER }}@${{ secrets.EC2_BASTION_HOST }} << 'EOF'
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/app
            git push origin main
            mvn clean package
            java -jar target/cloud-storage-app-0.0.1-SNAPSHOT.jar &
          EOF
        EOF



    - name: Restart Nginx and App
      run: |
        ssh -A ${{ secrets.EC2_BASTION_USER }}@${{ secrets.EC2_BASTION_HOST }} << 'EOF'
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/app
            mvn clean package
            java -jar target/cloud-storage-app-0.0.1-SNAPSHOT.jar &
          EOF
        EOF
